### ISSUE TITLE
Empty link titles

### ISSUE THREAD

**Issue by illus0r** [KevinBockelandt/notoire#28]
Hey there!

Your plugin is great, I look forward to using it for my zettelkasten!

There is a small problem. When I select a word (i.e. `hello`) and hit `<ledder>n`, the new page is created and opened instantly. It's ok by now. But if I go back with `<ledder>k` I see the newly created link without title (`[](b)`), whereas I expect to see `[hello](b)`

<img width='400' src='https://user-images.githubusercontent.com/797993/85932737-b315f580-b8df-11ea-9033-43cb127e94cb.gif' />

Would also be great if :NotoireCreateEmptyLink 
1. created a link to selected note but didn't open it instantly,
2. used first line of selected note as a title of the link (i.e. `[hello](b)` instead `[](b)`)

Thanks again for you efforts making such a great tool!

**Comment by KevinBockelandt** [comment]
Hi! Thanks for you feedback.

Regarding the 1st point it's actually the intended behavior of the function. Maybe it's not explained that clearly in the doc but the goal with `:NotoireCreateNote` is to be able to visually select a portion of a note and move it to it's own new note, leaving a link behind.

This is why the text for the link is left empty since we cannot know how you want to reference that new note in the link.

To do what you are looking for you should use `:NotoireCreateLink` and select `NEW` in the list.

You can think of it as:

- `:NotoireCreateNote` -> "I want to create a note with the selected text"
- `:NotoireCreateLink` -> "I want to create a link with the selected text"

Have you tried the "split" versions of commands? You can run `:NotoireCreateEmptyLinkVSplit` for example in order to keep the note you are working on open.

I'm afraid using the first line of notes as title for links could lead to problems. For example I start some of my notes straight away. Meaning the first line is actually a whole paragraph of text.

Tell me if it's allright for you :)

**Comment by illus0r** [comment]
Kevin, thank you for the elaborate answer!
`:NotoireCreateLink` suits my needs pretty well, I wonder how I missed it.

I really like your idea of getting rid of the titles, dates and other metadata. It makes things really simple.
